Repository CoolPeace-yanolza/backend, pull requests merged in 2024-01, with the labels that each got.

#10 Role 엔티티 및 타입 추가
  src/main/java/com/coolpeace/domain/member/entity/Member.java
  src/main/java/com/coolpeace/domain/member/entity/MemberRole.java
  src/main/java/com/coolpeace/domain/member/entity/Role.java
  src/main/java/com/coolpeace/domain/member/entity/key/MemberRoleId.java
  src/main/java/com/coolpeace/domain/member/entity/type/RoleType.java
  src/main/java/com/coolpeace/domain/member/repository/MemberRepository.java
  src/main/java/com/coolpeace/domain/member/repository/RoleRepository.java
Labels: feature

#14 jwt 서비스 및 필터 추가
  build.gradle
  src/main/java/com/coolpeace/global/config/SecurityConfig.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
  src/main/java/com/coolpeace/global/jwt/dto/JwtPair.java
  src/main/java/com/coolpeace/global/jwt/dto/JwtPayload.java
  src/main/java/com/coolpeace/global/jwt/exception/InvalidAuthorizationHeaderException.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtAuthenticationException.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtExpiredAuthorizationException.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtInvalidSignatureException.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtMalformedStructureException.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtUnsupportedFormatException.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationConverter.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationProvider.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationToken.java
  src/main/java/com/coolpeace/global/jwt/security/JwtFilter.java
  src/main/java/com/coolpeace/global/jwt/security/JwtPrincipal.java
  src/main/java/com/coolpeace/global/jwt/security/JwtUserDetailsService.java
  src/main/java/com/coolpeace/global/jwt/service/JwtService.java
  src/main/resources/application.yaml
Labels: feature

#16 멤버 관련 컨트롤러 및 서비스 추가
  src/main/java/com/coolpeace/domain/member/controller/MemberController.java
  src/main/java/com/coolpeace/domain/member/dto/request/MemberLoginRequest.java
  src/main/java/com/coolpeace/domain/member/dto/request/MemberRegisterEmailCheckRequest.java
  src/main/java/com/coolpeace/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/coolpeace/domain/member/dto/request/RefreshAccessTokenRequest.java
  src/main/java/com/coolpeace/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/coolpeace/domain/member/dto/response/MemberRefreshAccessTokenResponse.java
  src/main/java/com/coolpeace/domain/member/dto/response/MemberRegisterResponse.java
  src/main/java/com/coolpeace/domain/member/entity/Member.java
  src/main/java/com/coolpeace/domain/member/entity/Role.java
  src/main/java/com/coolpeace/domain/member/exception/MemberAlreadyExistedException.java
  src/main/java/com/coolpeace/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/coolpeace/domain/member/exception/MemberRoleNotFoundException.java
  src/main/java/com/coolpeace/domain/member/exception/MemberWrongPasswordException.java
  src/main/java/com/coolpeace/domain/member/repository/MemberRepository.java
  src/main/java/com/coolpeace/domain/member/service/MemberService.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
  src/main/java/com/coolpeace/global/jwt/dto/JwtPair.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationConverter.java
  src/main/java/com/coolpeace/global/jwt/security/JwtPrincipal.java
  src/main/java/com/coolpeace/global/jwt/security/JwtUserDetailsService.java
  src/main/java/com/coolpeace/global/jwt/service/JwtService.java
  src/main/resources/import.sql
  src/test/http/checkEmail.http
  src/test/http/login.http
  src/test/http/logout.http
  src/test/http/refreshToken.http
  src/test/http/register.http
Labels: feature

#26 actions CD 스크립트 수정
  .github/workflows/CD.yml
Labels: invalid

#19 Redis에 리프레시 토큰 저장 및 블랙리스트 기능 추가
  src/main/java/com/coolpeace/domain/member/controller/MemberController.java
  src/main/java/com/coolpeace/domain/member/entity/Member.java
  src/main/java/com/coolpeace/domain/member/entity/MemberRole.java
  src/main/java/com/coolpeace/domain/member/entity/key/MemberRoleId.java
  src/main/java/com/coolpeace/domain/member/service/MemberService.java
  src/main/java/com/coolpeace/global/config/ArgumentResolversConfig.java
  src/main/java/com/coolpeace/global/config/RedisConfig.java
  src/main/java/com/coolpeace/global/config/SecurityConfig.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
  src/main/java/com/coolpeace/global/exception/ErrorMessage.java
  src/main/java/com/coolpeace/global/exception/GlobalExceptionHandler.java
  src/main/java/com/coolpeace/global/jwt/entity/JwtBlackListRedisEntity.java
  src/main/java/com/coolpeace/global/jwt/entity/JwtRefreshTokenRedisEntity.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtExpiredRefreshTokenException.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtInvalidAccessTokenException.java
  src/main/java/com/coolpeace/global/jwt/exception/JwtInvalidRefreshTokenException.java
  src/main/java/com/coolpeace/global/jwt/repository/JwtBlackListRedisRepository.java
  src/main/java/com/coolpeace/global/jwt/repository/JwtRefreshTokenRedisRepository.java
  src/main/java/com/coolpeace/global/jwt/repository/RedisRepository.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationConverter.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationProvider.java
  src/main/java/com/coolpeace/global/jwt/security/JwtAuthenticationToken.java
  src/main/java/com/coolpeace/global/jwt/security/JwtPrincipal.java
  src/main/java/com/coolpeace/global/jwt/service/JwtService.java
  src/main/java/com/coolpeace/global/resolver/AuthJwtCredential.java
  src/main/java/com/coolpeace/global/resolver/AuthJwtCredentialArgumentResolver.java
  src/main/java/com/coolpeace/global/resolver/AuthJwtPrincipal.java
  src/main/java/com/coolpeace/global/resolver/AuthJwtPrincipalArgumentResolver.java
  src/test/java/com/coolpeace/global/jwt/repository/JwtRefreshTokenRedisRepositoryTest.java
Labels: feature

#25 쿠폰 레포,서비스 추가 및 일간 리포트 구현
  build.gradle
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponDailyRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponDailyResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/CouponDailyCondition.java
  src/main/java/com/coolpeace/domain/coupon/entity/CouponStatus.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepository.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
Labels: feature

#28 멤버 엔티티에 이름 필드 추가
  src/main/java/com/coolpeace/domain/member/controller/MemberController.java
  src/main/java/com/coolpeace/domain/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/coolpeace/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/coolpeace/domain/member/dto/response/MemberRegisterResponse.java
  src/main/java/com/coolpeace/domain/member/entity/Member.java
  src/main/java/com/coolpeace/domain/member/service/MemberService.java
  src/test/http/register.http
Labels: feature

#38 통계용 엔티티 추가
  src/main/java/com/coolpeace/domain/statistics/entity/DailyStatistics.java
  src/main/java/com/coolpeace/domain/statistics/entity/MonthlyStatistics.java
Labels: feature

#40 restdocs 의존성 추가
  .gitignore
  build.gradle
  src/main/java/com/coolpeace/global/config/SecurityConfig.java
  src/main/resources/static/swagger-ui/favicon-16x16.png
  src/main/resources/static/swagger-ui/favicon-32x32.png
  src/main/resources/static/swagger-ui/index.css
  src/main/resources/static/swagger-ui/index.html
  src/main/resources/static/swagger-ui/swagger-initializer.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js.map
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js.map
  src/main/resources/static/swagger-ui/swagger-ui.css
  src/main/resources/static/swagger-ui/swagger-ui.css.map
  src/test/java/com/coolpeace/docs/SampleControllerTest.java
  src/test/resources/import.sql
Labels: documentation

#41 Batch를 이용한 일별 통계 구현
  build.gradle
  src/main/java/com/coolpeace/CoolPeaceApplication.java
  src/main/java/com/coolpeace/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/coolpeace/domain/batch/job/StatisticsJob.java
  src/main/java/com/coolpeace/domain/batch/scheduler/BatchScheduler.java
  src/main/java/com/coolpeace/domain/batch/tasklet/CouponTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/ReservationTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/SettlementTasklet.java
  src/main/java/com/coolpeace/domain/reservation/entity/Reservation.java
  src/main/java/com/coolpeace/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/coolpeace/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/coolpeace/domain/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/coolpeace/domain/room/repository/RoomReservationRepository.java
  src/main/java/com/coolpeace/domain/settlement/entity/Settlement.java
  src/main/java/com/coolpeace/domain/settlement/repository/SettlementRepository.java
  src/main/java/com/coolpeace/domain/statistics/entity/DailyStatistics.java
  src/main/java/com/coolpeace/domain/statistics/entity/MonthlyStatistics.java
  src/main/java/com/coolpeace/domain/statistics/exception/DailyStatisticsNotFoundException.java
  src/main/java/com/coolpeace/domain/statistics/exception/MonthlyStatisticsNotFoundException.java
  src/main/java/com/coolpeace/domain/statistics/repository/DailyStatisticsRepository.java
  src/main/java/com/coolpeace/domain/statistics/repository/MonthlyStatisticsRepository.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
Labels: feature

#46 월별 통계 구현
  src/main/java/com/coolpeace/domain/accommodation/exception/AccommodationNotFoundException.java
  src/main/java/com/coolpeace/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/coolpeace/domain/batch/job/CustomStepListener.java
  src/main/java/com/coolpeace/domain/batch/job/DailyStatisticsConfig.java
  src/main/java/com/coolpeace/domain/batch/job/MonthlyStatisticsConfig.java
  src/main/java/com/coolpeace/domain/batch/scheduler/BatchScheduler.java
  src/main/java/com/coolpeace/domain/batch/tasklet/CouponDownloadTop3Tasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/LocalCouponDownloadTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/MonthlySumTasklet.java
  src/main/java/com/coolpeace/domain/statistics/entity/DailyStatistics.java
  src/main/java/com/coolpeace/domain/statistics/entity/LocalCouponDownload.java
  src/main/java/com/coolpeace/domain/statistics/entity/MonthlyStatistics.java
  src/main/java/com/coolpeace/domain/statistics/repository/DailyStatisticsRepository.java
  src/main/java/com/coolpeace/domain/statistics/repository/LocalCouponDownloadRepository.java
  src/main/java/com/coolpeace/domain/statistics/repository/MonthlyStatisticsRepository.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: feature

#49 쿠폰 도메인 관련 디테일 수정
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponExposeRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponRecentHistoryResponse.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponSearchResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponIssuerType.java
  src/main/java/com/coolpeace/domain/coupon/exception/InvalidCouponStateInsideExposureDateException.java
  src/main/java/com/coolpeace/domain/coupon/exception/InvalidCouponStateOutsideExposureDateException.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
Labels: feature

#50 JWT 인증 관련 유닛 테스트 코드 추가
  build.gradle
  src/main/java/com/coolpeace/domain/member/repository/MemberRepository.java
  src/main/java/com/coolpeace/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/coolpeace/domain/member/repository/MemberRepositoryImpl.java
  src/test/java/com/coolpeace/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/coolpeace/domain/member/service/MemberServiceTest.java
  src/test/java/com/coolpeace/global/common/QueryDSLRepositoryTest.java
  src/test/java/com/coolpeace/global/config/TestQueryDSLConfig.java
  src/test/java/com/coolpeace/global/factory/MemberTestBuilder.java
Labels: test

#51 쿠폰 대시보드 API 구현
  src/main/java/com/coolpeace/domain/accommodation/exception/AccommodationNotMatchMemberException.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponDailyRequest.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/dashboard/controller/DashboardController.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/ByYearCumulativeDataResponse.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/CumulativeDataResponse.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/MonthlyCouponDownloadResponse.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/MonthlyDataLightResponse.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/MonthlyDataResponse.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/WeeklyCouponResponse.java
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
  src/main/java/com/coolpeace/domain/statistics/repository/MonthlyStatisticsRepository.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
Labels: feature

#55 정산 조회 로직 및 API 구현
  src/main/java/com/coolpeace/domain/accommodation/exception/AccommodationNotMatchMemberException.java
  src/main/java/com/coolpeace/domain/batch/job/MonthlyStatisticsConfig.java
  src/main/java/com/coolpeace/domain/batch/scheduler/BatchScheduler.java
  src/main/java/com/coolpeace/domain/batch/tasklet/CompleteSettlementTasklet.java
  src/main/java/com/coolpeace/domain/settlement/controller/SettlementController.java
  src/main/java/com/coolpeace/domain/settlement/dto/request/SearchSettlementParams.java
  src/main/java/com/coolpeace/domain/settlement/dto/response/SettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/dto/response/SumSettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/entity/Settlement.java
  src/main/java/com/coolpeace/domain/settlement/repository/OrderBy.java
  src/main/java/com/coolpeace/domain/settlement/repository/SettlementRepository.java
  src/main/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryCustom.java
  src/main/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryImpl.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/main/java/com/coolpeace/domain/statistics/repository/DailyStatisticsRepository.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
Labels: feature

#60 숙소 주소, 연관관계 엔티티 수정, API 추가
  src/main/java/com/coolpeace/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/coolpeace/domain/accommodation/dto/response/AccomodationResponse.java
  src/main/java/com/coolpeace/domain/accommodation/dto/response/RoomResponse.java
  src/main/java/com/coolpeace/domain/accommodation/entity/Accommodation.java
  src/main/java/com/coolpeace/domain/accommodation/entity/Sido.java
  src/main/java/com/coolpeace/domain/accommodation/entity/Sigungu.java
  src/main/java/com/coolpeace/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/coolpeace/domain/accommodation/service/AccomodationService.java
  src/main/java/com/coolpeace/domain/room/entity/Room.java
  src/main/java/com/coolpeace/domain/room/entity/RoomReservation.java
  src/main/java/com/coolpeace/domain/room/repository/RoomRepository.java
Labels: feature

#65 개발 테스트용 데이터 생성
  src/main/java/com/coolpeace/domain/accommodation/entity/Sido.java
  src/main/java/com/coolpeace/domain/accommodation/entity/Sigungu.java
  src/main/resources/import.sql
Labels: test

#66 회원 로그인 시 응답에 email 정보 추가
  src/main/java/com/coolpeace/domain/member/dto/response/MemberLoginResponse.java
  src/main/java/com/coolpeace/domain/member/service/MemberService.java
  src/test/java/com/coolpeace/docs/member/MemberControllerTest.java
Labels: feature

#64 쿠폰 도메인 통합 테스트 작성
  src/main/java/com/coolpeace/domain/accommodation/entity/Accommodation.java
  src/main/java/com/coolpeace/domain/accommodation/entity/Sido.java
  src/main/java/com/coolpeace/domain/accommodation/entity/Sigungu.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/room/entity/Room.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/docs/member/MemberControllerTest.java
  src/test/java/com/coolpeace/docs/utils/AccommodationTestUtil.java
  src/test/java/com/coolpeace/docs/utils/MemberTestUtil.java
  src/test/java/com/coolpeace/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/coolpeace/domain/member/service/MemberServiceTest.java
  src/test/java/com/coolpeace/global/builder/AccommodationTestBuilder.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
  src/test/java/com/coolpeace/global/builder/MemberTestBuilder.java
  src/test/java/com/coolpeace/global/builder/RoomTestBuilder.java
  src/test/java/com/coolpeace/global/common/RestDocsIntegrationTest.java
Labels: test

#68 정산 유닛 테스트 구현
  src/main/java/com/coolpeace/domain/accommodation/entity/Accommodation.java
  src/main/java/com/coolpeace/domain/settlement/controller/SettlementController.java
  src/main/java/com/coolpeace/domain/settlement/dto/response/SettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/entity/Settlement.java
  src/main/java/com/coolpeace/domain/settlement/repository/SettlementRepository.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/main/java/com/coolpeace/domain/statistics/entity/DailyStatistics.java
  src/main/java/com/coolpeace/domain/statistics/entity/MonthlyStatistics.java
  src/test/java/com/coolpeace/docs/settlement/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/controller/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryTest.java
  src/test/java/com/coolpeace/domain/settlement/service/SettlementServiceTest.java
  src/test/java/com/coolpeace/global/config/RestDocsUnitTest.java
Labels: test, refactor

#76 서버 모니터링 도구 추가 및 swagger ui 스크립트 수정
  build.gradle
  src/main/java/com/coolpeace/global/config/SecurityConfig.java
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
  src/main/resources/static/swagger-ui/swagger-initializer.js
Labels: bug, feature

#78 CD 테스트 자동화 배포
  .github/workflows/CD.yml
  build.gradle
  src/main/java/com/coolpeace/global/config/SecurityConfig.java
  src/main/resources/application.yaml
  src/main/resources/logback-spring.xml
  src/main/resources/static/swagger-ui/swagger-initializer.js
Labels: release

#93 swagger ui 401 에러 관련 build.gradle 수정
  .github/workflows/CD.yml
  build.gradle
Labels: bug

#94 swagger 관련 수정 버전 release
  .github/workflows/CD.yml
  build.gradle
Labels: release

#95 쿠폰 조회, 이전 쿠폰 등록 내역 조회 시 요청과 응답 관련 수정
  .github/workflows/CD.yml
  build.gradle
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CouponRoomTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CustomerTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DayOfWeekRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DiscountTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/config/ConverterConfig.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
Labels: feature

#96 쿠폰 조회(검색) 관련 및 swagger ui URL 관련 수정사항 반영 release
  .github/workflows/CD.yml
  build.gradle
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CouponRoomTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CustomerTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DayOfWeekRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DiscountTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/config/ConverterConfig.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
Labels: release

#97 쿠폰 대시보드 유닛, resd docs 테스트 구현
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/dashboard/controller/DashboardController.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/MonthlyDataResponse.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/WeeklyCouponResponse.java
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
  src/main/java/com/coolpeace/domain/statistics/entity/LocalCouponDownload.java
  src/main/java/com/coolpeace/domain/statistics/repository/MonthlyStatisticsRepository.java
  src/main/java/com/coolpeace/domain/statistics/repository/MonthlyStatisticsRepositoryCustom.java
  src/main/java/com/coolpeace/domain/statistics/repository/MonthlyStatisticsRepositoryImpl.java
  src/test/java/com/coolpeace/docs/dashboard/DashboardControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponQueryServiceTest.java
  src/test/java/com/coolpeace/domain/dashboard/controller/DashboardControllerTest.java
  src/test/java/com/coolpeace/domain/dashboard/repository/DashboardRepositoryTest.java
  src/test/java/com/coolpeace/domain/dashboard/service/DashboardServiceTest.java
  src/test/java/com/coolpeace/domain/settlement/service/SettlementServiceTest.java
Labels: feature, test

#98 쿠폰 도메인 서비스 유닛 테스트 추가
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/SearchCouponParams.java
  src/main/java/com/coolpeace/domain/coupon/exception/InvalidCouponStateEndExposureDateException.java
  src/main/java/com/coolpeace/domain/coupon/exception/InvalidCouponStateInsideExposureDateException.java
  src/main/java/com/coolpeace/domain/coupon/exception/InvalidCouponStateWaitExposureDateException.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/domain/room/exception/RegisterRoomsEmptyException.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: test

#102 테스트 id 검증 삭제
  src/test/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryTest.java
  src/test/java/com/coolpeace/domain/settlement/service/SettlementServiceTest.java
Labels: bug

#103 Accommodation 조회 API 문서 생성
  src/main/java/com/coolpeace/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/coolpeace/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/coolpeace/domain/accommodation/dto/response/RoomResponse.java
  src/main/java/com/coolpeace/domain/accommodation/service/AccomodationService.java
  src/test/java/com/coolpeace/docs/accommodation/AccommodationControllerTest.java
Labels: test

#105 쿠폰 레포지토리 테스트 추가
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRoomsRepository.java
  src/test/java/com/coolpeace/docs/accommodation/AccommodationControllerTest.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/docs/dashboard/DashboardControllerTest.java
  src/test/java/com/coolpeace/docs/member/MemberControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/repository/CouponRepositoryTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponQueryServiceTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/domain/dashboard/controller/DashboardControllerTest.java
  src/test/java/com/coolpeace/global/util/CouponTestUtil.java
  src/test/java/com/coolpeace/global/util/MemberTestUtil.java
  src/test/java/com/coolpeace/global/util/RoomTestUtil.java
Labels: test

#106 쿠폰 수정 시 유효성 체크 추가
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponUpdateRequestValidator.java
Labels: feature

#101 변경점에 따른 일간, 월간 통계 구현
  src/main/java/com/coolpeace/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/coolpeace/domain/accommodation/repository/AccommodationRepositoryCustom.java
  src/main/java/com/coolpeace/domain/accommodation/repository/AccommodationRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepository.java
  src/main/java/com/coolpeace/domain/statistics/entity/LocalCouponDownload.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
  src/test/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryTest.java
Labels: feature, refactor

#111 쿠폰 조회 응답에 쿠폰 카테고리 추가
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponCategoryResponse.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponSearchResponse.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
Labels: feature

#113 2024-01-13 release
  README.md
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponCategoryResponse.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponSearchResponse.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/resources/application.yaml
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
Labels: release

#115 build.gradle에서 openapi3 관련 스크립트 수정
  build.gradle
  src/test/resources/security.yaml
Labels: bug, documentation

#118 숙소 타입 추가
  src/main/java/com/coolpeace/domain/accommodation/entity/Accommodation.java
  src/main/java/com/coolpeace/domain/accommodation/entity/type/AccommodationType.java
  src/main/resources/import.sql
Labels: feature

#123 예약 내역 CRD 추가
  src/main/java/com/coolpeace/domain/reservation/controller/ReservationController.java
  src/main/java/com/coolpeace/domain/reservation/dto/request/ReservationCreateRequest.java
  src/main/java/com/coolpeace/domain/reservation/dto/request/ReservationStatusChangeRequest.java
  src/main/java/com/coolpeace/domain/reservation/dto/response/ReservationPageResponse.java
  src/main/java/com/coolpeace/domain/reservation/dto/response/ReservationResponse.java
  src/main/java/com/coolpeace/domain/reservation/entity/Reservation.java
  src/main/java/com/coolpeace/domain/reservation/entity/type/ReservationStatusType.java
  src/main/java/com/coolpeace/domain/reservation/exception/ReservationNotFoundException.java
  src/main/java/com/coolpeace/domain/reservation/service/ReservationService.java
  src/main/java/com/coolpeace/domain/room/entity/RoomReservation.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
Labels: feature

#125 테스트 데이터 추가
  src/main/java/com/coolpeace/domain/room/entity/RoomReservation.java
  src/main/resources/import.sql
Labels: test

#133 정산 통계 로직 수정 및 통계 서비스 로직 변경
  src/main/java/com/coolpeace/domain/batch/job/MonthlyStatisticsConfig.java
  src/main/java/com/coolpeace/domain/batch/tasklet/CompleteSettlementTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/CouponTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/LocalCouponAvgTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/LocalCouponDownloadTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/ReservationTasklet.java
  src/main/java/com/coolpeace/domain/batch/tasklet/SettlementTasklet.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepository.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/dashboard/controller/DashboardController.java
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
  src/main/java/com/coolpeace/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/com/coolpeace/domain/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/com/coolpeace/domain/settlement/controller/SettlementController.java
  src/main/java/com/coolpeace/domain/settlement/dto/request/SearchSettlementParams.java
  src/main/java/com/coolpeace/domain/settlement/entity/SearchDate.java
  src/main/java/com/coolpeace/domain/settlement/repository/OrderBy.java
  src/main/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryCustom.java
  src/main/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryImpl.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/main/java/com/coolpeace/domain/statistics/controller/StatisticsController.java
  src/main/java/com/coolpeace/domain/statistics/entity/LocalCouponDownload.java
  src/main/java/com/coolpeace/domain/statistics/repository/LocalCouponDownloadRepository.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
  src/test/java/com/coolpeace/docs/settlement/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/dashboard/service/DashboardServiceTest.java
  src/test/java/com/coolpeace/domain/settlement/controller/SettlementControllerTest.java
Labels: feature, refactor

#135 쿠폰 도메인 DTO의 enum 값을 요청/응답 시에 한글 값으로 받도록 수정
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponExposeRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/SearchCouponParams.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CouponRoomTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CustomerTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DayOfWeekRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DiscountTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/SearchCouponDateFilterType.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/SearchCouponStatusFilterType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponIssuerType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponRoomType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponStatusType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CustomerType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/DiscountType.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/common/DayOfWeekUtil.java
  src/main/java/com/coolpeace/global/common/ValuedEnum.java
  src/main/java/com/coolpeace/global/common/validator/ValidEnum.java
  src/main/java/com/coolpeace/global/common/validator/ValuedEnumValidator.java
  src/main/java/com/coolpeace/global/config/ConverterConfig.java
  src/test/http/coupons/search.http
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/repository/CouponRepositoryTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
Labels: feature

#136 2024-01-19 release
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponExposeRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/SearchCouponParams.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CouponRoomTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/CustomerTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DayOfWeekRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/converter/DiscountTypeRequestConverter.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/SearchCouponDateFilterType.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/SearchCouponStatusFilterType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponIssuerType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponRoomType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponStatusType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CustomerType.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/DiscountType.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/common/DayOfWeekUtil.java
  src/main/java/com/coolpeace/global/common/ValuedEnum.java
  src/main/java/com/coolpeace/global/common/validator/ValidEnum.java
  src/main/java/com/coolpeace/global/common/validator/ValuedEnumValidator.java
  src/main/java/com/coolpeace/global/config/ConverterConfig.java
  src/test/http/coupons/search.http
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/repository/CouponRepositoryTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
Labels: release

#140 쿠폰 노출 여부 수정 메소드에서 ON/OFF만 요청받도록 수정
  src/main/java/com/coolpeace/domain/coupon/exception/CouponUpdateLimitExposureStateException.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: feature

#138 Batch 일간 통계 버그 해결 및 코드 개선
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
  src/main/java/com/coolpeace/domain/settlement/entity/SearchDate.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/main/java/com/coolpeace/domain/statistics/entity/DailySearchDate.java
  src/main/java/com/coolpeace/domain/statistics/entity/MonthlySearchDate.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
Labels: bug, feature

#144 대시보드 월별 데이터 오류 수정
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
Labels: bug

#148 쿠폰 조회 관련 수정
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/SearchCouponParams.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/global/common/validator/ValidEnum.java
  src/main/java/com/coolpeace/global/common/validator/ValuedEnumValidator.java
Labels: bug

#149 01.20 배포
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/SearchCouponParams.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/global/common/validator/ValidEnum.java
  src/main/java/com/coolpeace/global/common/validator/ValuedEnumValidator.java
Labels: release

#150 쿠폰 조회 관련 이슈의 잘못된 조건 수정
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/global/common/validator/ValuedEnumValidator.java
Labels: bug

#151 01.20 2차 배포
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/global/common/validator/ValuedEnumValidator.java
Labels: release

#155 쿠폰 조회 관련 수정
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
Labels: feature

#154 정산 조회 수정
  src/main/java/com/coolpeace/domain/settlement/dto/response/SettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/entity/Settlement.java
  src/test/java/com/coolpeace/docs/settlement/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/controller/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryTest.java
  src/test/java/com/coolpeace/domain/settlement/service/SettlementServiceTest.java
Labels: feature, refactor

#156 01-22 AM 11시 배포
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/domain/settlement/dto/response/SettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/entity/Settlement.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/docs/settlement/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/controller/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryTest.java
  src/test/java/com/coolpeace/domain/settlement/service/SettlementServiceTest.java
Labels: release

#160 쿠폰 도메인 싱크업
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/controller/CouponSearchController.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: bug, feature

#162 쿠폰 도메인 싱크업
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
Labels: feature

#161 01-22 16시 배포
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/controller/CouponSearchController.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: release

#163 정산 조회 API 수정
  src/main/java/com/coolpeace/domain/settlement/dto/response/PageSettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/dto/response/SettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/entity/Settlement.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/test/java/com/coolpeace/docs/settlement/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/controller/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/repository/SettlementRepositoryTest.java
  src/test/java/com/coolpeace/domain/settlement/service/SettlementServiceTest.java
Labels: feature, refactor

#167 쿠폰 카테고리 개수 조회 쿼리 수정
  src/main/java/com/coolpeace/domain/coupon/controller/CouponSearchController.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: bug

#168 1.22 19시 배포
  src/main/java/com/coolpeace/domain/coupon/controller/CouponSearchController.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: release

#169 쿠폰 카테고리 관련 수정
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: bug

#170 캐싱이 필요한 API 캐싱 구현
  src/main/java/com/coolpeace/CoolPeaceApplication.java
  src/main/java/com/coolpeace/domain/accommodation/service/AccomodationService.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/WrapMonthlyDataResponse.java
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
  src/main/java/com/coolpeace/global/config/RedisCacheConfig.java
  src/test/java/com/coolpeace/docs/dashboard/DashboardControllerTest.java
  src/test/java/com/coolpeace/domain/dashboard/controller/DashboardControllerTest.java
  src/test/java/com/coolpeace/domain/dashboard/service/DashboardServiceTest.java
Labels: feature

#174 쿠폰 상태 Batch 작업
  src/main/java/com/coolpeace/domain/batch/job/DailyStatisticsConfig.java
  src/main/java/com/coolpeace/domain/batch/tasklet/CouponStatusTasklet.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
Labels: feature

#172 쿠폰 할인 유형 관련 싱크업
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRegisterRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponUpdateRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: feature

#175 1.23 14시 30분 배포
  src/main/java/com/coolpeace/CoolPeaceApplication.java
  src/main/java/com/coolpeace/domain/accommodation/service/AccomodationService.java
  src/main/java/com/coolpeace/domain/batch/job/DailyStatisticsConfig.java
  src/main/java/com/coolpeace/domain/batch/tasklet/CouponStatusTasklet.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRegisterRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponUpdateRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/domain/dashboard/dto/response/WrapMonthlyDataResponse.java
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/main/java/com/coolpeace/domain/statistics/service/DailyStatisticsService.java
  src/main/java/com/coolpeace/domain/statistics/service/MonthlyStatisticsService.java
  src/main/java/com/coolpeace/global/config/RedisCacheConfig.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/docs/dashboard/DashboardControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/domain/dashboard/controller/DashboardControllerTest.java
  src/test/java/com/coolpeace/domain/dashboard/service/DashboardServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: release

#177 숙소 캐싱 버그
  src/main/java/com/coolpeace/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/coolpeace/domain/accommodation/dto/response/WrapAccommodationResponse.java
  src/main/java/com/coolpeace/domain/accommodation/dto/response/WrapRoomResponse.java
  src/main/java/com/coolpeace/domain/accommodation/service/AccomodationService.java
  src/test/java/com/coolpeace/docs/accommodation/AccommodationControllerTest.java
Labels: bug

#180 쿠폰 객실 유형 관련 싱크업
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRegisterRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponUpdateRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: feature

#181 01.23 23시 배포
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRegisterRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponUpdateRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/coolpeace/global/builder/CouponTestBuilder.java
Labels: release

#187 정산 API 수정
  src/main/java/com/coolpeace/domain/settlement/dto/response/PageSettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/test/java/com/coolpeace/docs/settlement/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/controller/SettlementControllerTest.java
Labels: feature

#190 연도별 통계 API 오류 수정
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
Labels: bug

#188 1월 25일 16시 배포
  README.md
  docs/images/cool-peace-website.png
  docs/images/erd.png
  docs/images/gantt.png
  docs/images/infra.png
  docs/images/logo.png
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
  src/main/java/com/coolpeace/domain/settlement/dto/response/PageSettlementResponse.java
  src/main/java/com/coolpeace/domain/settlement/service/SettlementService.java
  src/main/java/com/coolpeace/global/config/CorsConfig.java
  src/test/java/com/coolpeace/docs/settlement/SettlementControllerTest.java
  src/test/java/com/coolpeace/domain/settlement/controller/SettlementControllerTest.java
Labels: release

#192 쿠폰 만료 요청 시 삭제된 쿠폰을 보여주지 않도록 수정
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: feature

#193 1월 25일 17시 배포
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: release

#196 1월 25일 18시 배포
  src/main/java/com/coolpeace/global/config/ActuatorHealthIndicator.java
Labels: release

#197 일간 쿠폰 리포트 수정
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
Labels: bug, refactor

#199 일간 쿠폰 리포트 상태 값 변경
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: refactor

#200 1월 25일 19시 배포
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: release

#202 쿠폰 등록, 수정, 조회 시 요청 응답 싱크업
  src/main/java/com/coolpeace/domain/coupon/dto/DtoCouponUtil.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/DtoCouponUseDayOfWeekType.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/DtoCouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRegisterRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponUpdateRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/common/DayOfWeekUtil.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
Labels: feature

#203 1월 25일 22시 배포
  src/main/java/com/coolpeace/domain/coupon/dto/DtoCouponUtil.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponUpdateRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/DtoCouponUseDayOfWeekType.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/type/DtoCouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRegisterRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/validator/CouponUpdateRequestValidator.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/common/DayOfWeekUtil.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
Labels: release

#206 [bugfix] 연도별 데이터 key 값 변경
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
Labels: bug

#207 1월 26일 14시 배포
  src/main/java/com/coolpeace/domain/dashboard/service/DashboardService.java
Labels: release

#208 쿠폰 상태 변경 쿼리 수정
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
Labels: bug

#209 1월 26일 15시 배포
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
Labels: release

#211 [refactor] 일간 쿠폰 리포트 캐싱 삭제
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: bug, refactor

#212 1월 26일 18시 배포
  src/main/java/com/coolpeace/domain/coupon/service/CouponQueryService.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
Labels: release

#214 쿠폰 도메인 관련 싱크업
  src/main/java/com/coolpeace/domain/coupon/dto/DtoCouponUtil.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
Labels: feature

#215 1월 27일 18시 30분 배포
  src/main/java/com/coolpeace/domain/coupon/dto/DtoCouponUtil.java
  src/main/java/com/coolpeace/domain/coupon/dto/request/CouponRegisterRequest.java
  src/main/java/com/coolpeace/domain/coupon/dto/response/CouponResponse.java
  src/main/java/com/coolpeace/domain/coupon/entity/Coupon.java
  src/main/java/com/coolpeace/domain/coupon/entity/type/CouponUseDaysType.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/test/java/com/coolpeace/docs/coupon/CouponControllerTest.java
  src/test/java/com/coolpeace/domain/coupon/service/CouponServiceTest.java
Labels: release

#217 쿠폰 조회 관련 싱크업
  src/main/java/com/coolpeace/domain/coupon/controller/CouponSearchController.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
Labels: release

#218 1월 27일 21시 배포
  src/main/java/com/coolpeace/domain/coupon/controller/CouponSearchController.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryCustom.java
  src/main/java/com/coolpeace/domain/coupon/repository/CouponRepositoryImpl.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponService.java
  src/main/java/com/coolpeace/global/exception/ErrorCode.java
Labels: release

#220 TimZone 한국시간으로 세팅
  src/main/java/com/coolpeace/CoolPeaceApplication.java
Labels: bug

#221 1월 28일 1시 배포
  src/main/java/com/coolpeace/CoolPeaceApplication.java
Labels: release

#222 일별 통계 API에 쿠폰 상태 변경 서비스 로직 추가
  src/main/java/com/coolpeace/domain/statistics/controller/StatisticsController.java
Labels: feature

#223 일별 통계 API에 쿠폰 노출 종료 상태 변경 서비스 로직 추가
  src/main/java/com/coolpeace/domain/statistics/controller/StatisticsController.java
Labels: refactor

#226 CouponGuestService 추가
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponGuestService.java
  src/main/java/com/coolpeace/global/jwt/security/JwtPrincipal.java
Labels: feature

#227 1월 30일 5시 배포
  README.md
  src/main/java/com/coolpeace/domain/coupon/controller/CouponController.java
  src/main/java/com/coolpeace/domain/coupon/service/CouponGuestService.java
  src/main/java/com/coolpeace/domain/statistics/controller/StatisticsController.java
  src/main/java/com/coolpeace/global/jwt/security/JwtPrincipal.java
Labels: release
